// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AppendFunctionTail : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static AppendFunctionTail GetRootAsAppendFunctionTail(ByteBuffer _bb) { return GetRootAsAppendFunctionTail(_bb, new AppendFunctionTail()); }
  public static AppendFunctionTail GetRootAsAppendFunctionTail(ByteBuffer _bb, AppendFunctionTail obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AppendFunctionTail __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Funcea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TailEaStart { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong TailEaEnd { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.AppendFunctionTail> CreateAppendFunctionTail(FlatBufferBuilder builder,
      ulong funcea = 0,
      ulong tailEaStart = 0,
      ulong tailEaEnd = 0) {
    builder.StartTable(3);
    AppendFunctionTail.AddTailEaEnd(builder, tailEaEnd);
    AppendFunctionTail.AddTailEaStart(builder, tailEaStart);
    AppendFunctionTail.AddFuncea(builder, funcea);
    return AppendFunctionTail.EndAppendFunctionTail(builder);
  }

  public static void StartAppendFunctionTail(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddFuncea(FlatBufferBuilder builder, ulong funcea) { builder.AddUlong(0, funcea, 0); }
  public static void AddTailEaStart(FlatBufferBuilder builder, ulong tailEaStart) { builder.AddUlong(1, tailEaStart, 0); }
  public static void AddTailEaEnd(FlatBufferBuilder builder, ulong tailEaEnd) { builder.AddUlong(2, tailEaEnd, 0); }
  public static Offset<protocol.sync.AppendFunctionTail> EndAppendFunctionTail(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.AppendFunctionTail>(o);
  }
};


}
