// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ChangeExtraComment : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ChangeExtraComment GetRootAsChangeExtraComment(ByteBuffer _bb) { return GetRootAsChangeExtraComment(_bb, new ChangeExtraComment()); }
  public static ChangeExtraComment GetRootAsChangeExtraComment(ByteBuffer _bb, ChangeExtraComment obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ChangeExtraComment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Line { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Comment { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCommentBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetCommentBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetCommentArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<protocol.sync.ChangeExtraComment> CreateChangeExtraComment(FlatBufferBuilder builder,
      ulong ea = 0,
      int line = 0,
      StringOffset commentOffset = default(StringOffset)) {
    builder.StartTable(3);
    ChangeExtraComment.AddEa(builder, ea);
    ChangeExtraComment.AddComment(builder, commentOffset);
    ChangeExtraComment.AddLine(builder, line);
    return ChangeExtraComment.EndChangeExtraComment(builder);
  }

  public static void StartChangeExtraComment(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static void AddLine(FlatBufferBuilder builder, int line) { builder.AddInt(1, line, 0); }
  public static void AddComment(FlatBufferBuilder builder, StringOffset commentOffset) { builder.AddOffset(2, commentOffset.Value, 0); }
  public static Offset<protocol.sync.ChangeExtraComment> EndChangeExtraComment(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.ChangeExtraComment>(o);
  }
};


}
