// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ChangeItem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ChangeItem GetRootAsChangeItem(ByteBuffer _bb) { return GetRootAsChangeItem(_bb, new ChangeItem()); }
  public static ChangeItem GetRootAsChangeItem(ByteBuffer _bb, ChangeItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ChangeItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Type { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTypeArray() { return __p.__vector_as_array<byte>(6); }
  public string Names { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNamesBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNamesBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNamesArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<protocol.sync.ChangeItem> CreateChangeItem(FlatBufferBuilder builder,
      ulong ea = 0,
      StringOffset typeOffset = default(StringOffset),
      StringOffset namesOffset = default(StringOffset)) {
    builder.StartTable(3);
    ChangeItem.AddEa(builder, ea);
    ChangeItem.AddNames(builder, namesOffset);
    ChangeItem.AddType(builder, typeOffset);
    return ChangeItem.EndChangeItem(builder);
  }

  public static void StartChangeItem(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(1, typeOffset.Value, 0); }
  public static void AddNames(FlatBufferBuilder builder, StringOffset namesOffset) { builder.AddOffset(2, namesOffset.Value, 0); }
  public static Offset<protocol.sync.ChangeItem> EndChangeItem(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.ChangeItem>(o);
  }
};


}
