// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CreateStruct : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CreateStruct GetRootAsCreateStruct(ByteBuffer _bb) { return GetRootAsCreateStruct(_bb, new CreateStruct()); }
  public static CreateStruct GetRootAsCreateStruct(ByteBuffer _bb, CreateStruct obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CreateStruct __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public bool IsUnion { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<protocol.sync.CreateStruct> CreateCreateStruct(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      bool isUnion = false) {
    builder.StartTable(2);
    CreateStruct.AddName(builder, nameOffset);
    CreateStruct.AddIsUnion(builder, isUnion);
    return CreateStruct.EndCreateStruct(builder);
  }

  public static void StartCreateStruct(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddIsUnion(FlatBufferBuilder builder, bool isUnion) { builder.AddBool(1, isUnion, false); }
  public static Offset<protocol.sync.CreateStruct> EndCreateStruct(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.CreateStruct>(o);
  }
};


}
