// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DeleteStruct : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DeleteStruct GetRootAsDeleteStruct(ByteBuffer _bb) { return GetRootAsDeleteStruct(_bb, new DeleteStruct()); }
  public static DeleteStruct GetRootAsDeleteStruct(ByteBuffer _bb, DeleteStruct obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeleteStruct __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<protocol.sync.DeleteStruct> CreateDeleteStruct(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    DeleteStruct.AddName(builder, nameOffset);
    return DeleteStruct.EndDeleteStruct(builder);
  }

  public static void StartDeleteStruct(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<protocol.sync.DeleteStruct> EndDeleteStruct(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.DeleteStruct>(o);
  }
};


}
