// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DeleteFunction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DeleteFunction GetRootAsDeleteFunction(ByteBuffer _bb) { return GetRootAsDeleteFunction(_bb, new DeleteFunction()); }
  public static DeleteFunction GetRootAsDeleteFunction(ByteBuffer _bb, DeleteFunction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeleteFunction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.DeleteFunction> CreateDeleteFunction(FlatBufferBuilder builder,
      ulong ea = 0) {
    builder.StartTable(1);
    DeleteFunction.AddEa(builder, ea);
    return DeleteFunction.EndDeleteFunction(builder);
  }

  public static void StartDeleteFunction(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static Offset<protocol.sync.DeleteFunction> EndDeleteFunction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.DeleteFunction>(o);
  }
};


}
