// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MakeCode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MakeCode GetRootAsMakeCode(ByteBuffer _bb) { return GetRootAsMakeCode(_bb, new MakeCode()); }
  public static MakeCode GetRootAsMakeCode(ByteBuffer _bb, MakeCode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MakeCode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.MakeCode> CreateMakeCode(FlatBufferBuilder builder,
      ulong ea = 0) {
    builder.StartTable(1);
    MakeCode.AddEa(builder, ea);
    return MakeCode.EndMakeCode(builder);
  }

  public static void StartMakeCode(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static Offset<protocol.sync.MakeCode> EndMakeCode(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.MakeCode>(o);
  }
};


}
