// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MakeData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MakeData GetRootAsMakeData(ByteBuffer _bb) { return GetRootAsMakeData(_bb, new MakeData()); }
  public static MakeData GetRootAsMakeData(ByteBuffer _bb, MakeData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MakeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint Flags { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Length { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ulong Tid { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.MakeData> CreateMakeData(FlatBufferBuilder builder,
      ulong ea = 0,
      uint flags = 0,
      uint length = 0,
      ulong tid = 0) {
    builder.StartTable(4);
    MakeData.AddTid(builder, tid);
    MakeData.AddEa(builder, ea);
    MakeData.AddLength(builder, length);
    MakeData.AddFlags(builder, flags);
    return MakeData.EndMakeData(builder);
  }

  public static void StartMakeData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static void AddFlags(FlatBufferBuilder builder, uint flags) { builder.AddUint(1, flags, 0); }
  public static void AddLength(FlatBufferBuilder builder, uint length) { builder.AddUint(2, length, 0); }
  public static void AddTid(FlatBufferBuilder builder, ulong tid) { builder.AddUlong(3, tid, 0); }
  public static Offset<protocol.sync.MakeData> EndMakeData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.MakeData>(o);
  }
};


}
