// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

public enum OperandType : sbyte
{
  Unsupported = -1,
  Unknown = 0,
  Enum = 1,
  StructOffset = 2,
  Offset = 3,
};


}
