// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SetFunctionEnd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SetFunctionEnd GetRootAsSetFunctionEnd(ByteBuffer _bb) { return GetRootAsSetFunctionEnd(_bb, new SetFunctionEnd()); }
  public static SetFunctionEnd GetRootAsSetFunctionEnd(ByteBuffer _bb, SetFunctionEnd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetFunctionEnd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Startea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Endea { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.SetFunctionEnd> CreateSetFunctionEnd(FlatBufferBuilder builder,
      ulong startea = 0,
      ulong endea = 0) {
    builder.StartTable(2);
    SetFunctionEnd.AddEndea(builder, endea);
    SetFunctionEnd.AddStartea(builder, startea);
    return SetFunctionEnd.EndSetFunctionEnd(builder);
  }

  public static void StartSetFunctionEnd(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddStartea(FlatBufferBuilder builder, ulong startea) { builder.AddUlong(0, startea, 0); }
  public static void AddEndea(FlatBufferBuilder builder, ulong endea) { builder.AddUlong(1, endea, 0); }
  public static Offset<protocol.sync.SetFunctionEnd> EndSetFunctionEnd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.SetFunctionEnd>(o);
  }
};


}
