// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SetFunctionStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static SetFunctionStart GetRootAsSetFunctionStart(ByteBuffer _bb) { return GetRootAsSetFunctionStart(_bb, new SetFunctionStart()); }
  public static SetFunctionStart GetRootAsSetFunctionStart(ByteBuffer _bb, SetFunctionStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetFunctionStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ea { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Newea { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<protocol.sync.SetFunctionStart> CreateSetFunctionStart(FlatBufferBuilder builder,
      ulong ea = 0,
      ulong newea = 0) {
    builder.StartTable(2);
    SetFunctionStart.AddNewea(builder, newea);
    SetFunctionStart.AddEa(builder, ea);
    return SetFunctionStart.EndSetFunctionStart(builder);
  }

  public static void StartSetFunctionStart(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEa(FlatBufferBuilder builder, ulong ea) { builder.AddUlong(0, ea, 0); }
  public static void AddNewea(FlatBufferBuilder builder, ulong newea) { builder.AddUlong(1, newea, 0); }
  public static Offset<protocol.sync.SetFunctionStart> EndSetFunctionStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.sync.SetFunctionStart>(o);
  }
};


}
