// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.sync
{

public enum StructMemberType : sbyte
{
  Data = 0,
  Struct = 1,
  String = 2,
  Enum = 3,
  Offset = 4,
};


}
