// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONSTANTS_PROTOCOL_CONSTANTS_H_
#define FLATBUFFERS_GENERATED_CONSTANTS_PROTOCOL_CONSTANTS_H_

#include "flatbuffers/flatbuffers.h"

namespace protocol {
namespace constants {

enum ProtocolVersion {
  ProtocolVersion_V_1_0 = 10,
  ProtocolVersion_MIN = ProtocolVersion_V_1_0,
  ProtocolVersion_MAX = ProtocolVersion_V_1_0
};

inline const ProtocolVersion (&EnumValuesProtocolVersion())[1] {
  static const ProtocolVersion values[] = {
    ProtocolVersion_V_1_0
  };
  return values;
}

inline const char * const *EnumNamesProtocolVersion() {
  static const char * const names[2] = {
    "V_1_0",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocolVersion(ProtocolVersion e) {
  if (flatbuffers::IsOutRange(e, ProtocolVersion_V_1_0, ProtocolVersion_V_1_0)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(ProtocolVersion_V_1_0);
  return EnumNamesProtocolVersion()[index];
}

}  // namespace constants
}  // namespace protocol

#endif  // FLATBUFFERS_GENERATED_CONSTANTS_PROTOCOL_CONSTANTS_H_
