// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DISCONNECTREASON_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_DISCONNECTREASON_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace protocol {

enum DisconnectReason {
  DisconnectReason_Quit = 0,
  DisconnectReason_Kicked = 1,
  DisconnectReason_BadPassword = 2,
  DisconnectReason_BadConnection = 3,
  DisconnectReason_TimedOut = 4,
  DisconnectReason_MIN = DisconnectReason_Quit,
  DisconnectReason_MAX = DisconnectReason_TimedOut
};

inline const DisconnectReason (&EnumValuesDisconnectReason())[5] {
  static const DisconnectReason values[] = {
    DisconnectReason_Quit,
    DisconnectReason_Kicked,
    DisconnectReason_BadPassword,
    DisconnectReason_BadConnection,
    DisconnectReason_TimedOut
  };
  return values;
}

inline const char * const *EnumNamesDisconnectReason() {
  static const char * const names[6] = {
    "Quit",
    "Kicked",
    "BadPassword",
    "BadConnection",
    "TimedOut",
    nullptr
  };
  return names;
}

inline const char *EnumNameDisconnectReason(DisconnectReason e) {
  if (flatbuffers::IsOutRange(e, DisconnectReason_Quit, DisconnectReason_TimedOut)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDisconnectReason()[index];
}

}  // namespace protocol

#endif  // FLATBUFFERS_GENERATED_DISCONNECTREASON_PROTOCOL_H_
