// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.constants
{

public enum ProtocolVersion : int
{
  V_1_0 = 10,
};


}
