// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.constants
{

public enum ProtocolVersion : int
{
  Current = 10,
};


}
