// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum DisconnectReason : uint
{
  None = 0,
  Quit = 1,
  Kicked = 2,
  BadPassword = 3,
  BadConnection = 4,
  TimedOut = 5,
};


}
