// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum DisconnectReason : uint
{
  Quit = 0,
  Kicked = 1,
  BadPassword = 2,
  BadConnection = 3,
  TimedOut = 4,
};


}
