// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MessageRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MessageRoot GetRootAsMessageRoot(ByteBuffer _bb) { return GetRootAsMessageRoot(_bb, new MessageRoot()); }
  public static MessageRoot GetRootAsMessageRoot(ByteBuffer _bb, MessageRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MessageRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.Data DataType { get { int o = __p.__offset(4); return o != 0 ? (protocol.Data)__p.bb.Get(o + __p.bb_pos) : protocol.Data.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }

  public static Offset<protocol.MessageRoot> CreateMessageRoot(FlatBufferBuilder builder,
      protocol.Data data_type = protocol.Data.NONE,
      int dataOffset = 0) {
    builder.StartTable(2);
    MessageRoot.AddData(builder, dataOffset);
    MessageRoot.AddDataType(builder, data_type);
    return MessageRoot.EndMessageRoot(builder);
  }

  public static void StartMessageRoot(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDataType(FlatBufferBuilder builder, protocol.Data dataType) { builder.AddByte(0, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
  public static Offset<protocol.MessageRoot> EndMessageRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.MessageRoot>(o);
  }
  public static void FinishMessageRootBuffer(FlatBufferBuilder builder, Offset<protocol.MessageRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMessageRootBuffer(FlatBufferBuilder builder, Offset<protocol.MessageRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
