// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum MsgType : byte
{
  NONE = 0,
  HandshakeRequest = 1,
  HandshakeAck = 2,
  Announcement = 3,
  ChatMessage = 4,
  LocalProject = 5,
  RemoteProject = 6,
  sync_NameEa = 7,
  sync_AddFunction = 8,
  sync_DeleteFunction = 9,
  sync_SetFunctionStart = 10,
  sync_SetFunctionEnd = 11,
  sync_AppendFunctionTail = 12,
  sync_DeleteFunctionTail = 13,
  sync_ChangeFunctionTailOwner = 14,
  sync_ChangeItemComment = 15,
  sync_ChangeRangeComment = 16,
  sync_ChangeExtraComment = 17,
  sync_CreateEnum = 18,
  sync_DeleteEnum = 19,
  sync_CreateStruct = 20,
  sync_RenameStruct = 21,
  sync_DeleteStruct = 22,
  sync_RenameStructMember = 23,
  sync_DeleteStructMember = 24,
  sync_ChangeStructMember = 25,
  sync_ChangeItem = 26,
  sync_MakeCode = 27,
  sync_MakeData = 28,
  sync_Undefine = 29,
  sync_ChangeOperand = 30,
};


}
