// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum MsgType : byte
{
  NONE = 0,
  HandshakeRequest = 1,
  HandshakeAck = 2,
  sync_NameAddr = 3,
};


}
