name: CI

on:
  push:
    branches: [ "main", "devel3" ]
  pull_request:
    branches: [ "main", "devel3" ]

jobs:
    MSVC:
      runs-on: windows-latest
      strategy:
        matrix:
          config: [Debug, Shipping]
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Build
        shell: powershell
        run: |
          .\build\premake_win.cmd
          $vcvarsall_path = .\build\bin\win\vswhere.exe -find VC\Auxiliary\Build\vcvarsall.bat
          cmd /c """$vcvarsall_path"" x86_amd64 & set" | foreach {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }
          msbuild .\out\vs2022\Equilibrium.sln /t:'base\base:Rebuild;base\base_memory_unittests:Rebuild;base\base_unittests:Rebuild' /p:Configuration=${{ matrix.config }} /p:Platform=x64 -m
      - name: Test
        run: Get-ChildItem -Path (Resolve-Path .\out\vs*\bin\*\equilibrium\) -Filter *.exe | ForEach-Object $_ { $p = @(); $p += '--gtest_color=no '; $p += '--gtest_output=xml:.\tests\' + $_.Name.Replace('.exe','') + '.xml'; &$_.PSPath $p; }
      - name: Convert Gtest to JUnit
        if: success() || failure()
        shell: powershell
        run: |
          $xsl = New-Object System.Xml.Xsl.XslCompiledTransform
          $xsl.Load("${{github.workspace}}\.github\gtest_to_junit.xsl")
          Get-ChildItem -Path .\tests\ -Filter *.xml | Where-Object { !$_.Name.StartsWith('convert') } | ForEach-Object $_ { $xsl.Transform($_.FullName,($_.Directory.FullName  + '\convert-' + $_.Name)); }
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: .\tests\convert-*.xml

    Linux:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          config: [Debug, Shipping]
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'
      - name: Setup C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler-version: '16'
      - name: Build
        run: |
          ./build/premake_linux.sh
          cd out/gmake2
          make