name: CI

on:
  workflow_dispatch:
    inputs:
      remote_debug:
        type: boolean
        description: 'Run TMate if Building or Testing fails. (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
    branches: [ "main", "devel5"]
  pull_request:
    branches: [ "main", "devel5" ]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
        build_type: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        fetch-depth: '1'
    - name: Configure
      run: cmake -S . -B build-cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DEQ_BUILD_TESTS=ON
    - name: Build
      run: cmake --build build-cmake --config ${{ matrix.build_type }} --parallel
    - name: Test
      run: ctest --test-dir build-cmake --build-config ${{ matrix.build_type }} --output-on-failure --no-tests=error
    - name: Setup tmate debug session
      if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.remote_debug}}
      uses: mxschmitt/action-tmate@v3
