name: Generate version

on:
  push:
    branches:
      - coderelease
      
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history, including tags'
          set-safe-directory: 'true'
      - name: Set it again
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Tag stuff with version-it
        uses: Force67/version.it@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}