// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum AnnounceType : sbyte
{
  FirstJoin = 0,
  Joined = 1,
  Disconnect = 2,
};


}
