// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum MsgType : byte
{
  NONE = 0,
  HandshakeRequest = 1,
  HandshakeAck = 2,
  Announcement = 3,
  ChatMessage = 4,
  LocalProjectInfo = 5,
  RemoteProjectInfo = 6,
  WorkspaceList = 7,
  TransferBegin = 8,
  TransferChunk = 9,
  sync_NameEa = 10,
  sync_AddFunction = 11,
  sync_DeleteFunction = 12,
  sync_SetFunctionStart = 13,
  sync_SetFunctionEnd = 14,
  sync_AppendFunctionTail = 15,
  sync_DeleteFunctionTail = 16,
  sync_ChangeFunctionTailOwner = 17,
  sync_ChangeItemComment = 18,
  sync_ChangeRangeComment = 19,
  sync_ChangeExtraComment = 20,
  sync_CreateEnum = 21,
  sync_DeleteEnum = 22,
  sync_CreateStruct = 23,
  sync_RenameStruct = 24,
  sync_DeleteStruct = 25,
  sync_RenameStructMember = 26,
  sync_DeleteStructMember = 27,
  sync_ChangeStructMember = 28,
  sync_ChangeItem = 29,
  sync_MakeCode = 30,
  sync_MakeData = 31,
  sync_Undefine = 32,
  sync_ChangeOperand = 33,
};


}
