// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

[System.FlagsAttribute]
public enum UserPermissions : byte
{
  Guest = 1,
  Reporter = 2,
  Developer = 4,
  Master = 8,
};


}
