// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct WorkspaceList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static WorkspaceList GetRootAsWorkspaceList(ByteBuffer _bb) { return GetRootAsWorkspaceList(_bb, new WorkspaceList()); }
  public static WorkspaceList GetRootAsWorkspaceList(ByteBuffer _bb, WorkspaceList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WorkspaceList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.Project? Projects(int j) { int o = __p.__offset(4); return o != 0 ? (protocol.Project?)(new protocol.Project()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ProjectsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<protocol.WorkspaceList> CreateWorkspaceList(FlatBufferBuilder builder,
      VectorOffset projectsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    WorkspaceList.AddProjects(builder, projectsOffset);
    return WorkspaceList.EndWorkspaceList(builder);
  }

  public static void StartWorkspaceList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddProjects(FlatBufferBuilder builder, VectorOffset projectsOffset) { builder.AddOffset(0, projectsOffset.Value, 0); }
  public static VectorOffset CreateProjectsVector(FlatBufferBuilder builder, Offset<protocol.Project>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateProjectsVectorBlock(FlatBufferBuilder builder, Offset<protocol.Project>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartProjectsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<protocol.WorkspaceList> EndWorkspaceList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.WorkspaceList>(o);
  }
};


}
