// Copyright (C) Force67 <github.com/Force67>.
// For licensing information see LICENSE at the root of this distribution.
#pragma once

#include <base/files/file_util.h>

namespace base {

class ScopedTempDir {
 public:
  ScopedTempDir();
  ~ScopedTempDir();

  bool CreateUniqueTempDir();
  bool Delete();

  fs::path& Path();

  // Returns the prefix used for temp directory names generated by
  // ScopedTempDirs.
  static const fs::path::value_type* GetTempDirPrefix();
 private:
  fs::path path_;
};
}  // namespace base